name: 'TiddlyWiki-CodeMirror-Enhanced'

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README*.md'
      - 'media/**'
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README*.md'
      - 'media/**'

jobs:
  build:
    name: Build TiddlyWiki Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Python3
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Set up NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Minify/Rollup Extensions
        run: npm install uglify-js clean-css-cli rollup -g

      - name: Install NPM Dependencies
        run: npm install

      - name: Packup TS Core Project
        run: cd src/core && rollup -c && cd ../..

      - name: Build Plugin
        run: python build.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/*.json
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
